### ISSUE TITLE
I want to ask you about the usage of smetana.

### ISSUE THREAD

**Issue by ChenCongZ** [qikongwanli/qi#1]
Hi @qikongwanli, 
The pipeline I used is in SBML format (pathway tools), but I can't read the file. So I want to ask you to teach me.

**Comment by qikongwanli** [comment]
> Hi @qikongwanli, The pipeline I used is in SBML format (pathway tools), but I can't read the file. So I want to ask you to teach me.
Can you paste the codes and the error codes? 

When you load you model, you should take a look at the following parameters "--flavor "
Please make sure which format of model, cobra or fbc2? 
I think you can try both.  --flavor cobra      or    --flavor fbc2

**Comment by ChenCongZ** [comment]
![Screenshot_2023-03-22_04-23-52](https://user-images.githubusercontent.com/98649346/226825901-d0d27291-383d-4dae-8359-90053dfc1f01.png)
I entered the relevant command but encountered this problem.

**Comment by ChenCongZ** [comment]
[GCF_001435755 .txt](https://github.com/qikongwanli/qi/files/11037292/GCF_001435755.txt)

**Comment by ChenCongZ** [comment]
my data format seems different from his test data format.

**Comment by qikongwanli** [comment]
> my data format seems different from his test data format.

The format of models should be .xml. You can generate model by carveme.

**Comment by ChenCongZ** [comment]
hello @qikongwanli,
 I don't seem to be able to use carveme. 
![Screenshot_2023-03-23_04-05-43](https://user-images.githubusercontent.com/98649346/227122866-6bbd65b2-add4-4cf1-aaf9-0f9d580f6aca.png)

**Comment by ChenCongZ** [comment]
cplex seems that it needs to be purchased.

**Comment by qikongwanli** [comment]
> cplex seems that it needs to be purchased.

You can download cplex from internet

**Comment by qikongwanli** [comment]
> cplex seems that it needs to be purchased.

You can download cplex from internet

**Comment by ChenCongZ** [comment]
Hi @qikongwanli,
 Thank you for your help.
Can you give me a download link?

**Comment by ChenCongZ** [comment]
It seems that I found it wrong.

**Comment by ChenCongZ** [comment]
![QQ浏览器截图20230327095424](https://user-images.githubusercontent.com/98649346/227822463-ffd24627-c3a2-47c9-846e-9de7ab25d463.png)
